Oci support
openinfradev/helm2yaml pull request #8
Opened 2023-08-14 11:16 UTC by intelliguy

2023-08-14 12:13 UTC, ktkfree commented
어떤 변경인지 잘 모르겠지만, 금번에 prd harbor 구축한 곳에도 migration 필요해보입니다.

2023-08-18 00:46 UTC, robertchoi80 commented on Dockerfile
> +# Build CLI: docker build --network host -t siim/helm2yaml:v3.0.0 .
코멘트긴 하지만 개인 repo(siim) 보다는 공용 repo로 해두는게 좋겠습니다.

2023-08-18 00:47 UTC, robertchoi80 requested changes
제 코멘트랑 태규님 코멘트 반영해주시면 바로 머지할게요

2023-09-05 01:00 UTC, intelliguy commented on Dockerfile
> +# Build CLI: docker build --network host -t siim/helm2yaml:v3.0.0 .
메모와 같은 용도라서 의미는 없습니다.

2023-09-05 01:03 UTC, intelliguy commented
> 

이미지를 배포한 것으로 위 언급한 repo에 넣어뒀습니다.
harbor-cicd.taco-cat.xyz/tks/decapod-render:v3.0.0

2023-09-05 01:16 UTC, ktkfree approved these changes

2023-09-05 01:16 UTC, ktkfree commented
> > 
> 
> 이미지를 배포한 것으로 위 언급한 repo에 넣어뒀습니다. harbor-cicd.taco-cat.xyz/tks/decapod-render:v3.0.0

싱크에서 논의한대로 harbor.taco-cat.xyz 여기에도 넣어주세요~

2023-09-05 01:25 UTC, robertchoi80 commented on Dockerfile
> +# Build CLI: docker build --network host -t siim/helm2yaml:v3.0.0 .
지금 든 생각인데, 변경 내용 참고하려고 이렇게 넣으신 걸로 보이는데, 앞으로 또 변경 내역이 계속 생길 수 있을 테니 이렇게 인라인으로 넣는 것보다는 차라리 별도의 RELEASE 또는 CHANGELOG 파일에 기록하는게 어떨까 하는 생각이 듭니다.  물론 그때는 'docker build' 라인은 굳이 필요 없으니 지우면 될거 같구요

2023-09-05 02:09 UTC, intelliguy commented
완료했습니다.

2023-09-07 03:52 UTC, intelliguy commented on Dockerfile
> +# Build CLI: docker build --network host -t siim/helm2yaml:v3.0.0 .
이건 체계를 잡는 차원에서 팀내 공감대형성을 우선하고 진행해야 하는 내역으로 판단됩니다. 다음 회의에 주제로 잡아 진행해주세요.

2023-09-08 00:26 UTC, bluejayA commented on Dockerfile
> +# Build CLI: docker build --network host -t siim/helm2yaml:v3.0.0 .
우선은 이 repository readme가 현재 없는 상태이기도 하고, 간단하게 readme 만들면서, 넣도록 하죠. 
readme 에 대표적인 변경사항에 대한 이력을 기록하는 걸로 시작을 하면 되지 않을까 합니다.

2023-09-08 00:27 UTC, bluejayA commented on Dockerfile
> +# Build CLI: docker build --network host -t siim/helm2yaml:v3.0.0 .
readme 는 별도 pr로 간단하게 올려주시고, 이건 merge 시키도록 하죠.

2023-09-08 00:27 UTC, bluejayA approved these changes

2023-09-08 00:54 UTC, robertchoi80 commented
> 우선은 이 repository readme가 현재 없는 상태이기도 하고, 간단하게 readme 만들면서, 넣도록 하죠. readme 에 대표적인 변경사항에 대한 이력을 기록하는 걸로 시작을 하면 되지 않을까 합니다.
> readme 는 별도 pr로 간단하게 올려주시고, 이건 merge 시키도록 하죠.

팀장님 의견 참고로 다시 남기고, 머지합니다.

2023-09-08 00:55 UTC, robertchoi80 approved these changes

2023-09-08 00:55 UTC, merged